controller:
  kind: DaemonSet
  hostPort:
    enabled: true
  service:
    type: ClusterIP
  nodeSelector:
    ingress-ready: 'true'
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  admissionWebhooks:
    enabled: false
